Update secure.yaml
Signed-off-by: syslabtech <134613532+syslabtech@users.noreply.github.com>

diff --git a/.github/workflows/secure.yaml b/.github/workflows/secure.yaml
--- a/.github/workflows/secure.yaml
+++ b/.github/workflows/secure.yaml
@@ -31,11 +31,11 @@ jobs:
         run: |
           echo "Input matches secret!"
           
-      # - name: Check secret input
-      #   if: ${{ github.event.inputs.secret_input }} != ${{secrets.SECRET_TOKEN }}  # Corrected
-      #   run: |
-      #     echo "Invalid secret input!"
-      #     exit 1  # Terminate the workflow
+      - name: Check secret input
+        if: ${{ github.event.inputs.secret_input != secrets.SECRET_TOKEN }}  # Corrected
+        run: |
+          echo "Invalid secret input!"
+          exit 1  # Terminate the workflow
 
       # - name: Allowed actions
       #   if: ${{ github.event.inputs.secret_input }} == ${{secrets.SECRET_TOKEN }}  # Corrected
